name: Deploy to dev

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    name: Deploying everything to dev cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH Into server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -tt -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@15.206.80.178 "
            export NVM_DIR=\$HOME/.nvm &&
            source \$NVM_DIR/nvm.sh &&

            cd Test &&
            git pull &&

            pnpm install &&
            pnpm run build &&

            pm2 restart http-backend &&
            pm2 restart web &&
            pm2 restart ws-backend
          "
