name: Deploy to prod 

on:
  push:
    branches:
      - production

jobs:
    redeploy-everything:
        name: deploying everything to production cluster
        runs-on: ubuntu-latest

        steps:
            - name: SSH into Server
              run: |
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/ssh_key
                chmod 600 ~/ssh_key

                ssh -tt -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@35.154.24.126 "
                export NVM_DIR=\$HOME/.nvm &&
                source \$NVM_DIR/nvm.sh &&
                
                cd Test &&
                git pull &&

                pnpm install &&
                pnpm run build &&

                pm2 restart all
                "
